### ISSUE TITLE
Epic: Airshipui binary packaging

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#10]
As a user of airshipUI, I need a way to obtain the binary. This epic will have stories to ensure the multiple mechanisms to deliver airshipui as a binary are in place.
A Developer that takes on these stories can create the individual stories and their details.

- Story for including documentation
- Story for delivery of airshipui binary as a URl such as `curl -LO https://.../airship/airshipui/release/release/v2.0/bin/linux/amd64/airshipui`
- Story for delivery of arshipui as a a debian pkg : `sudo apt-get install airshipui`
- Story for CI/CD changes to build appropriate binary and or packages.

This is the airshipUI equivalent of [AIR-202](https://airship.atlassian.net/browse/AIR-202)

**Comment by jezogwza** [comment]
Potentially if we are going the route of integrating airship with octant via a script instead of a binary. Then the equivalent of that will be to provide an entry point to gather airshipui.
This might be an instruction set driven via a script that will :
- configure local environment
- pull the right version of octant
- provide the proper integration script
etc.
