### ISSUE TITLE
Airshipui not working effectively on windows

### ISSUE THREAD

**Issue by aschiefe** [airshipit/airshipui#15]
attempting to run the default build on windows does not work correctly:
```
C:\aic\airshipui>bin\airshipui help
'bin\airshipui' is not recognized as an internal or external command,
operable program or batch file.
```
If I use cygwin I can execute the airshipui binary but it does not find the kube config even when specified on the command line:
```
$ bin/airshipui --kubeconfig /cygdrive/c/Users/as3525/kube/config
2020-02-11T09:01:08.634-0600    ERROR   commands/dash.go:109    dashboard failed        {"err": "failed to init cluster client: invalid configuration: no configuration has been provided"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
        C:/aic/octant/internal/commands/dash.go:109
```
Ideally this would be cross compiled so that it is nativly executable on windows much in the same way that octant is.

**Comment by aschiefe** [comment]
Changed the makefile to output the .exe extension that windows needs.  There is a need fix the linting part of the makefile for windows.

It is possible that we should replace it with a build.go but that's something needing to be discussed yet.

**Comment by aschiefe** [comment]
Also needed to fix the linting installer

**Comment by aschiefe** [comment]
Compiling and executing on windows is not an issue but the integration with the current integration of argo is.  Network routing for the iframe is going to be difficult (currently unknown if it is even possible) on a local machine, and unclear if it will work on a remote machine.

**Comment by dotNomad** [comment]
Is development on Windows, including any Make commands not working, still an issue?

We haven't made any changes to create a .exe to windows, but it sounds like @aschiefe, you are able to execute with no issues?

As far as I understand the argo-ui plugin integration issue this is not specific to Windows, but instead a VPN and/or proxy issue due to the host machine not having direct access to Kubernetes endpoints. I'm not sure if this is an issue on Windows specifically.

If we can refine what actually needs to be worked on for Windows I think we can get some actionables on this issue.

**Comment by aschiefe** [comment]
The building and linting is working on windows with a few caveats there are some interop issues between cygwin and WSL, I can confirm it's working on cygwin but WSL curl has issues.  

I have an unmerged change to the makefile that corrects the behavior for windows.  I can push that up and we can close this and revisit once we get an idea of what we may need an end state to look like.

**Comment by dotNomad** [comment]
@aschiefe Ya please go ahead and push up the Makefile change so we can close this. Like you said we can revisit if changes need to happen.
